### ISSUE TITLE
Schedule and manually

### ISSUE THREAD

**Issue by benotje** [specialcircumstances/uk.co.iooop.logi#3]
What a good tool thanks for it !!!
What I noticed was the logi heating tool
the temp on 25 c set and I manually later on 22 c then the temp changed to 25 c within a minute
you understand my problem and there is something to be improved
I hope

**Comment by specialcircumstances** [comment]
Thanks @benotje - glad you like it. :)  Beta 2.0.1 should be out shortly too.
It's a good point you raise, this will indeed happen at the moment. I am planning to add a feature which will resolve this this week, so I guess it would make it to the app store sometime next week.
The feature will detect manual changes, and then pause any schedule updates for the affected thermostat for a set period of time - a couple of hours I guess (should make it configurable).
Eventually I'd like to add some sort of learning to the app, e.g. if you always change the temperature at 1900 on Saturdays to 21.5C then suggest the improvement to the schedule... that's a long way off though...

**Comment by specialcircumstances** [comment]
This has been added to beta 2.0.2, which I've just submitted for Athom approval. Should update automatically once published (probably a few days/early next week). Hope it's what you were after. Please give it a good test and let me know if it works for you OK. Thanks.
